version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          PGHOST: 127.0.0.1
          # PGHOST: localhost
          PGUSER: sweater_weather
          RAILS_ENV: test
          REDIS_URL: redis://redis@localhost:6379
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: sweater_weather
          POSTGRES_DB: sweater_weather_test
          POSTGRES_PASSWORD: POSTGRES_HOST_AUTH_METHOD=trust
      - image: circleci/redis:latest
    executor: ruby/default
    environment:
      key: ENV['key']
      appid: ENV['appid']
      api_key: ENV['api_key']
    steps:
      - checkout
      - restore_cache:
          keys:
            - location {{ .location }}
      # Setup the environment
      - run: gem install bundler:2.2.15
      - run: bundle config set --local path 'turing/mod3/projects/sweater_weather'
      - run: bundle install --path "turing/mod3/projects/sweater_weather"
      # DB Wait
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Redis Wait
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      # Run the test suite
      - run: bundle exec rspec